In [80]:
import pandas as pd
import numpy as np

In [81]:
orders = pd.read_csv("../Data/Raw/olist_orders_dataset.csv")
customers = pd.read_csv("../Data/Raw/olist_customers_dataset.csv")
order_items = pd.read_csv("../Data/Raw/olist_order_items_dataset.csv")
products = pd.read_csv("../Data/Raw/olist_products_dataset.csv")
payments = pd.read_csv("../Data/Raw/olist_order_payments_dataset.csv")

In [82]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [83]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [84]:
orders.describe()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-04-11 10:48:14,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-08 23:38:46,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

In [85]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [86]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [87]:
customers.describe()

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [88]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [89]:
order_items.info()
order_items.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [90]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [91]:
products.info()
products.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [92]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [93]:
payments.info()
payments.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [94]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [95]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [96]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [97]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [98]:
orders["order_purchase_timestamp"] = pd.to_datetime(orders["order_purchase_timestamp"])

In [99]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

**Merge orders+ customers+ products to create a sales table**

In [100]:
orders_customers = orders.merge(customers,on="customer_id", how="left")

In [101]:
orders_customers.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [102]:
sales = orders_customers.merge(
    order_items,
    on="order_id",
    how="left"
)

In [103]:
sales = sales.merge(products, on="product_id",how ="left")

In [104]:
sales.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,...,45.00,27.20,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,19.90,8.72,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0

In [105]:
sales["revenue"] = sales["price"] + sales["freight_value"]

In [106]:
sales_dataset = sales[
    [
        "order_id",
        "customer_unique_id",
        "order_purchase_timestamp",
        "product_category_name",
        "price",
        "freight_value",
        "revenue"
    ]
]

In [107]:
sales_dataset.head()

,order_id,customer_unique_id,order_purchase_timestamp,product_category_name,price,freight_value,revenue
0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,2017-10-02 10:56:33,utilidades_domesticas,29.99,8.72,38.71
1,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,2018-07-24 20:41:37,perfumaria,118.70,22.76,141.46
2,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,2018-08-08 08:38:49,automotivo,159.90,19.22,179.12
3,949d5b44dbf5de918fe9c16f97b45f8a,7c142cf63193a1473d2e66489a9ae977,2017-11-18 19:28:06,pet_shop,45.00,27.20,72.20
4,ad21c59c0840e6cb83a9ceb5573f8159,72632f0f9dd73dfee390c9b22eb56dd6,2018-02-13 21:18:39,papelaria,19.90,8.72,28.62

In [108]:
sales_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113425 entries, 0 to 113424
Data columns (total 7 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  113425 non-null  object
 1   customer_unique_id        113425 non-null  object
 2   order_purchase_timestamp  113425 non-null  datetime64[ns]
 3   product_category_name     111047 non-null  object
 4   price                     112650 non-null  float64
 5   freight_value             112650 non-null  float64
 6   revenue                   112650 non-null  float64
dtypes: datetime64[ns](1), float64(3), object(3)
memory usage: 6.9+ MB

In [109]:
sales_dataset.isnull().sum()

order_id                       0
customer_unique_id             0
order_purchase_timestamp       0
product_category_name       2378
price                        775
freight_value                775
revenue                      775
dtype: int64

**Replace the missing category for the product category name**

In [110]:
sales_dataset["product_category_name"] = sales_dataset["product_category_name"].fillna("unknown")

/var/folders/cd/scfq7z155vzdzt8985s34bgh0000gn/T/ipykernel_43274/405248718.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_dataset["product_category_name"] = sales_dataset["product_category_name"].fillna("unknown")

In [111]:
sales_dataset = sales_dataset.dropna(subset=["price"])

In [112]:
sales_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112650 entries, 0 to 113424
Data columns (total 7 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  112650 non-null  object
 1   customer_unique_id        112650 non-null  object
 2   order_purchase_timestamp  112650 non-null  datetime64[ns]
 3   product_category_name     112650 non-null  object
 4   price                     112650 non-null  float64
 5   freight_value             112650 non-null  float64
 6   revenue                   112650 non-null  float64
dtypes: datetime64[ns](1), float64(3), object(3)
memory usage: 6.9+ MB

In [113]:
sales_dataset.isnull().sum()

order_id                    0
customer_unique_id          0
order_purchase_timestamp    0
product_category_name       0
price                       0
freight_value               0
revenue                     0
dtype: int64

## Recency, Frequenc, Monetary analysis (RFM)

In [114]:
reference_date = sales_dataset["order_purchase_timestamp"].max()
print(reference_date)

2018-09-03 09:06:57

In [115]:
rfm = sales_dataset.groupby("customer_unique_id").agg(
    {
        "order_purchase_timestamp": "max",
        "order_id": "nunique",
        "revenue":"sum"
    }
)
rfm.columns = ["last_purchase","frequency","monetary"]
rfm

                                       last_purchase  frequency  monetary
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2 2018-05-10 10:56:27          1    141.90
0000b849f77a49e4a4ce2b2a4ca5be3f 2018-05-07 11:11:27          1     27.19
0000f46a3911fa3c0805444483337064 2017-03-10 21:05:03          1     86.22
0000f6ccb0745a6a4b88665a16c9f078 2017-10-12 20:29:41          1     43.62
0004aac84e0df4da2b147fca70cf8255 2017-11-14 19:45:42          1    196.89
...                                              ...        ...       ...
fffcf5a5ff07b0908bd4e2dbc735a684 2017-06-08 21:00:36          1   2067.42
fffea47cd6d3cc0a88bd621562a9d061 2017-12-10 20:07:56          1     84.58
ffff371b4d645b6ecea244b27531430a 2017-02-07 15:49:16          1    112.46
ffff5962728ec6157033ef9805bacc48 2018-05-02 15:17:41          1    133.69
ffffd2657e2aad2907e67c3e9daecbeb 2017-05-02 20:18:45          1     71.56

[95420 rows x 3 columns]

In [116]:
rfm["recency"] = (reference_date - rfm["last_purchase"]).dt.days
rfm =rfm[["recency", "frequency", "monetary"]]

In [117]:
rfm.head()

                                  recency  frequency  monetary
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2      115          1    141.90
0000b849f77a49e4a4ce2b2a4ca5be3f      118          1     27.19
0000f46a3911fa3c0805444483337064      541          1     86.22
0000f6ccb0745a6a4b88665a16c9f078      325          1     43.62
0004aac84e0df4da2b147fca70cf8255      292          1    196.89

**Recency scoring**

In [118]:
rfm["r_score"] = pd.qcut(rfm["recency"],5,labels=[5,4,3,2,1])
rfm[["recency","r_score"]]

                                  recency r_score
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2      115       4
0000b849f77a49e4a4ce2b2a4ca5be3f      118       4
0000f46a3911fa3c0805444483337064      541       1
0000f6ccb0745a6a4b88665a16c9f078      325       2
0004aac84e0df4da2b147fca70cf8255      292       2
...                                   ...     ...
fffcf5a5ff07b0908bd4e2dbc735a684      451       1
fffea47cd6d3cc0a88bd621562a9d061      266       3
ffff371b4d645b6ecea244b27531430a      572       1
ffff5962728ec6157033ef9805bacc48      123       4
ffffd2657e2aad2907e67c3e9daecbeb      488       1

[95420 rows x 2 columns]

**Frequency scoring**

In [119]:
rfm["f_score"] = rfm["frequency"].apply(lambda x:
    1 if x == 1 else
    2 if x == 2 else
    3 if x == 3 else
    4 if x == 4 else
    5
)
rfm[["frequency","f_score"]]

                                  frequency  f_score
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2          1        1
0000b849f77a49e4a4ce2b2a4ca5be3f          1        1
0000f46a3911fa3c0805444483337064          1        1
0000f6ccb0745a6a4b88665a16c9f078          1        1
0004aac84e0df4da2b147fca70cf8255          1        1
...                                     ...      ...
fffcf5a5ff07b0908bd4e2dbc735a684          1        1
fffea47cd6d3cc0a88bd621562a9d061          1        1
ffff371b4d645b6ecea244b27531430a          1        1
ffff5962728ec6157033ef9805bacc48          1        1
ffffd2657e2aad2907e67c3e9daecbeb          1        1

[95420 rows x 2 columns]

In [120]:
rfm["frequency"].value_counts().head(10)

1     92507
2      2673
3       192
4        29
5         9
6         5
7         3
9         1
16        1
Name: frequency, dtype: int64

In [121]:
rfm["f_score"].value_counts().head(10)

1    92507
2     2673
3      192
4       29
5       19
Name: f_score, dtype: int64

**Monetary scoring**

In [122]:
rfm["m_score"] = pd.qcut(rfm["monetary"], 5, labels=[1,2,3,4,5])
rfm[["monetary","m_score"]]

                                  monetary m_score
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2    141.90       4
0000b849f77a49e4a4ce2b2a4ca5be3f     27.19       1
0000f46a3911fa3c0805444483337064     86.22       2
0000f6ccb0745a6a4b88665a16c9f078     43.62       1
0004aac84e0df4da2b147fca70cf8255    196.89       4
...                                    ...     ...
fffcf5a5ff07b0908bd4e2dbc735a684   2067.42       5
fffea47cd6d3cc0a88bd621562a9d061     84.58       2
ffff371b4d645b6ecea244b27531430a    112.46       3
ffff5962728ec6157033ef9805bacc48    133.69       4
ffffd2657e2aad2907e67c3e9daecbeb     71.56       2

[95420 rows x 2 columns]

**RFM scoring**

In [123]:
rfm["rfm_score"]= (rfm["r_score"].astype(str) + rfm["f_score"].astype(str) + rfm["m_score"].astype(str))
rfm

,recency,frequency,monetary,r_score,f_score,m_score,rfm_score
customer_unique_id,,,,,,,
0000366f3b9a7992bf8c76cfdf3221e2,115,1,141.90,4,1,4,414
0000b849f77a49e4a4ce2b2a4ca5be3f,118,1,27.19,4,1,1,411
0000f46a3911fa3c0805444483337064,541,1,86.22,1,1,2,112
0000f6ccb0745a6a4b88665a16c9f078,325,1,43.62,2,1,1,211
0004aac84e0df4da2b147fca70cf8255,292,1,196.89,2,1,4,214
...,...,...,...,...,...,...,...
fffcf5a5ff07b0908bd4e2dbc735a684,451,1,2067.42,1,1,5,115
fffea47cd6d3cc0a88bd621562a9d061,266,1,84.58,3,1,2,312
ffff371b4d645b6ecea244b27531430a,572,1,112.46,1,1,3,113
ffff5962728ec6157033ef9805bacc48,123,1,133.69,4,1,4,414
ffffd2657e2aad2907e67c3e9daecbeb,488,1,71.56,1,1,2,112

In [124]:
rfm["frequency"].max()

16

**Segment function**

In [125]:
def segment_customer(row):

    r = int(row["r_score"])
    f = int(row["f_score"])

    if r >= 4 and f >= 4:
        return "Champions" #recent and very frequent

    elif r >= 3 and f >= 3:
        return "Loyal Customers" #recent and frequent

    elif r >= 4 and f <= 2:
        return "Potential Loyalists" #recent and low frequency

    elif r <= 2 and f >= 3:    
        return "At Risk"  #old and mid frequency

    else:
        return "Lost"

In [126]:
rfm["segment"] = rfm.apply(segment_customer,axis =1)
rfm["segment"].value_counts()

Lost                   57125
Potential Loyalists    38055
Loyal Customers          134
At Risk                   72
Champions                 34
Name: segment, dtype: int64

**Exporting table**

In [127]:
rfm.reset_index(inplace=True)
#rfm.to_csv("rfm_segmentation.csv", index=False)

#Cohor Retention table creation#

In [128]:
sales_dataset["order_month"] = sales_dataset["order_purchase_timestamp"].dt.to_period("M")
first_purchase =sales_dataset.groupby("customer_unique_id")["order_month"].min()

In [129]:
sales_dataset = sales_dataset.merge(first_purchase, on="customer_unique_id", suffixes=("","_cohort"))
sales_dataset

,order_id,customer_unique_id,order_purchase_timestamp,product_category_name,price,freight_value,revenue,order_month,order_month_cohort
0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,2017-10-02 10:56:33,utilidades_domesticas,29.99,8.72,38.71,2017-10,2017-09
1,69923a4e07ce446644394df37a710286,7c396fd4830fd04220f754e42b4e5bff,2017-09-04 11:26:38,bebes,35.39,8.72,44.11,2017-09,2017-09
2,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,2018-07-24 20:41:37,perfumaria,118.70,22.76,141.46,2018-07,2018-07
3,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,2018-08-08 08:38:49,automotivo,159.90,19.22,179.12,2018-08,2018-08
4,949d5b44dbf5de918fe9c16f97b45f8a,7c142cf63193a1473d2e66489a9ae977,2017-11-18 19:28:06,pet_shop,45.00,27.20,72.20,2017-11,2017-11
...,...,...,...,...,...,...,...,...,...
112645,63943bddc261676b46f01ca7ac2f7bd8,da62f9e57a76d978d02ab5362c509660,2018-02-06 12:58:58,bebes,174.90,20.10,195.00,2018-02,2018-02
112646,83c1379a015df1e13d02aae0204711ab,737520a9aad80b3fbbdad19b66b37b30,2017-08-27 14:46:43,eletrodomesticos_2,205.99,65.02,271.01,2017-08,2017-08
112647,11c177c8e97725db2631073c19f07b62,5097a5312c8b157bb7be58ae360ef43c,2018-01-08 21:28:27,informatica_acessorios,179.99,40.59,220.58,2018-01,2018-01
112648,11c177c8e97725db2631073c19f07b62,5097a5312c8b157bb7be58ae360ef43c,2018-01-08 21:28:27,informatica_acessorios,179.99,40.59,220.58,2018-01,2018-01
112649,66dea50a8b16d9b4dee7af250b4be1a5,60350aa974b26ff12caad89e55993bd6,2018-03-08 20:57:30,beleza_saude,68.50,18.36,86.86,2018-03,2018-03

**Client age (cohort index)**

In [130]:
sales_dataset["cohort_index"] = (sales_dataset["order_month"].astype(int) - sales_dataset["order_month_cohort"].astype(int))
sales_dataset["cohort_index"].value_counts()

0     110248
1        542
2        379
3        255
4        228
5        171
6        169
7        135
8        104
9         97
10        94
11        69
12        40
14        29
13        29
15        28
17        17
16        11
19         3
20         2
Name: cohort_index, dtype: int64

**Calculate the cohort table**

In [131]:
cohort_data = sales_dataset.groupby(
    ["order_month_cohort", "cohort_index"]
)["customer_unique_id"].nunique().reset_index()

In [132]:
cohort_data

    order_month_cohort  cohort_index  customer_unique_id
0              2016-09             0                   3
1              2016-10             0                 305
2              2016-10             6                   1
3              2016-10             9                   1
4              2016-10            11                   1
..                 ...           ...                 ...
215            2018-06             2                  16
216            2018-07             0                6054
217            2018-07             1                  31
218            2018-08             0                6238
219            2018-08             1                   1

[220 rows x 3 columns]

**Transform the data in matrix (pivot)**

In [133]:
cohort_table = cohort_data.pivot(
    index="order_month_cohort",
    columns="cohort_index",
    values="customer_unique_id"
)
cohort_table

cohort_index,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20
order_month_cohort,,,,,,,,,,,,,,,,,,,,
2016-09,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-10,305.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0,2.0,2.0
2016-12,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01,754.0,3.0,2.0,1.0,3.0,1.0,3.0,1.0,1.0,NaN,3.0,1.0,5.0,3.0,1.0,1.0,2.0,3.0,1.0,NaN
2017-02,1705.0,4.0,5.0,2.0,7.0,2.0,4.0,3.0,2.0,3.0,2.0,5.0,2.0,3.0,2.0,1.0,1.0,4.0,NaN,NaN
2017-03,2595.0,13.0,9.0,10.0,9.0,4.0,4.0,8.0,9.0,2.0,10.0,3.0,6.0,3.0,4.0,6.0,2.0,4.0,NaN,NaN
2017-04,2339.0,14.0,5.0,4.0,8.0,6.0,8.0,7.0,7.0,4.0,6.0,2.0,2.0,1.0,2.0,2.0,4.0,NaN,NaN,NaN
2017-05,3560.0,17.0,17.0,14.0,11.0,12.0,15.0,5.0,9.0,10.0,9.0,12.0,9.0,1.0,7.0,9.0,NaN,NaN,NaN,NaN
2017-06,3114.0,15.0,11.0,12.0,8.0,12.0,12.0,7.0,4.0,7.0,10.0,11.0,5.0,4.0,6.0,NaN,NaN,NaN,NaN,NaN
2017-07,3843.0,20.0,14.0,9.0,11.0,8.0,12.0,4.0,7.0,10.0,8.0,11.0,5.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-08,4149.0,28.0,14.0,11.0,15.0,22.0,12.0,11.0,6.0,6.0,10.0,8.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-09,4090.0,28.0,22.0,12.0,18.0,9.0,9.0,10.0,12.0,7.0,11.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-10,4412.0,31.0,11.0,4.0,10.0,9.0,10.0,16.0,12.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11,7217.0,40.0,28.0,13.0,14.0,13.0,8.0,14.0,10.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12,5442.0,12.0,15.0,19.0,14.0,11.0,9.0,1.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01,6983.0,24.0,26.0,20.0,20.0,11.0,12.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02,6422.0,25.0,25.0,19.0,17.0,14.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-03,6947.0,31.0,22.0,20.0,9.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04,6709.0,39.0,21.0,16.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-05,6604.0,35.0,18.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-06,5934.0,25.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07,6054.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08,6238.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Retention rate**

In [134]:
cohort_size = cohort_table.iloc[:,0]
retention_table = cohort_table.divide(cohort_size, axis=0) *100
retention_table = retention_table.reindex(columns= range(0,21))
retention_table

cohort_index,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
order_month_cohort,,,,,,,,,,,,,,,,,,,,,
2016-09,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-10,100.0,NaN,NaN,NaN,NaN,NaN,0.327869,NaN,NaN,0.327869,...,0.327869,NaN,0.327869,NaN,0.327869,NaN,0.327869,NaN,0.655738,0.655738
2016-12,100.0,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01,100.0,0.397878,0.265252,0.132626,0.397878,0.132626,0.397878,0.132626,0.132626,NaN,...,0.132626,0.663130,0.397878,0.132626,0.132626,0.265252,0.397878,NaN,0.132626,NaN
2017-02,100.0,0.234604,0.293255,0.117302,0.410557,0.117302,0.234604,0.175953,0.117302,0.175953,...,0.293255,0.117302,0.175953,0.117302,0.058651,0.058651,0.234604,NaN,NaN,NaN
2017-03,100.0,0.500963,0.346821,0.385356,0.346821,0.154143,0.154143,0.308285,0.346821,0.077071,...,0.115607,0.231214,0.115607,0.154143,0.231214,0.077071,0.154143,NaN,NaN,NaN
2017-04,100.0,0.598546,0.213767,0.171013,0.342027,0.256520,0.342027,0.299273,0.299273,0.171013,...,0.085507,0.085507,0.042753,0.085507,0.085507,0.171013,NaN,NaN,NaN,NaN
2017-05,100.0,0.477528,0.477528,0.393258,0.308989,0.337079,0.421348,0.140449,0.252809,0.280899,...,0.337079,0.252809,0.028090,0.196629,0.252809,NaN,NaN,NaN,NaN,NaN
2017-06,100.0,0.481696,0.353243,0.385356,0.256904,0.385356,0.385356,0.224791,0.128452,0.224791,...,0.353243,0.160565,0.128452,0.192678,NaN,NaN,NaN,NaN,NaN,NaN
2017-07,100.0,0.520427,0.364299,0.234192,0.286235,0.208171,0.312256,0.104085,0.182149,0.260213,...,0.286235,0.130107,0.260213,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-08,100.0,0.674861,0.337431,0.265124,0.361533,0.530248,0.289226,0.265124,0.144613,0.144613,...,0.192818,0.096409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-09,100.0,0.684597,0.537897,0.293399,0.440098,0.220049,0.220049,0.244499,0.293399,0.171149,...,0.073350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-10,100.0,0.702629,0.249320,0.090662,0.226655,0.203989,0.226655,0.362647,0.271985,0.203989,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11,100.0,0.554247,0.387973,0.180130,0.193986,0.180130,0.110849,0.193986,0.138562,0.055425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12,100.0,0.220507,0.275634,0.349136,0.257258,0.202132,0.165380,0.018376,0.220507,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01,100.0,0.343692,0.372333,0.286410,0.286410,0.157525,0.171846,0.229128,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02,100.0,0.389287,0.389287,0.295858,0.264715,0.218001,0.202429,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-03,100.0,0.446236,0.316683,0.287894,0.129552,0.115158,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04,100.0,0.581309,0.313012,0.238486,0.134148,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-05,100.0,0.529982,0.272562,0.211993,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-06,100.0,0.421301,0.269633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07,100.0,0.512058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08,100.0,0.016031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Revenue per cohort table

In [135]:
revenu_cohort = sales_dataset.groupby(["order_month_cohort", "cohort_index"])["revenue"].sum().reset_index()
revenu_cohort

    order_month_cohort  cohort_index     revenue
0              2016-09             0      354.75
1              2016-10             0    56808.84
2              2016-10             6      111.30
3              2016-10             9      356.13
4              2016-10            11       56.78
..                 ...           ...         ...
215            2018-06             2     1893.08
216            2018-07             0  1034038.76
217            2018-07             1     4521.74
218            2018-08             0   980092.19
219            2018-08             1      166.46

[220 rows x 3 columns]

**Transform the data in matrix (pivot)**

In [136]:
revenue_cohort_table = revenu_cohort.pivot(index="order_month_cohort", columns="cohort_index",values = "revenue")
revenue_cohort_table

cohort_index,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20
order_month_cohort,,,,,,,,,,,,,,,,,,,,
2016-09,354.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-10,56808.84,NaN,NaN,NaN,NaN,NaN,111.30,NaN,NaN,356.13,NaN,56.78,NaN,163.53,NaN,381.00,NaN,116.57,384.01,181.37
2016-12,19.62,19.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01,137168.87,170.83,114.70,89.70,246.25,69.33,448.43,105.17,47.05,NaN,427.05,66.60,552.45,351.65,93.70,104.61,219.35,354.43,50.93,NaN
2017-02,286109.79,536.12,570.63,118.73,1151.96,74.21,688.92,274.30,464.61,385.35,343.22,454.39,279.24,397.11,181.66,136.79,291.68,536.16,NaN,NaN
2017-03,431397.77,1794.97,1737.12,1836.10,1213.97,1433.39,689.18,887.42,1447.49,237.96,1103.10,380.30,947.71,238.58,687.41,717.55,203.88,472.85,NaN,NaN
2017-04,409855.64,2937.00,940.40,758.21,1896.40,1208.34,2083.80,1096.55,963.99,499.82,692.56,343.17,488.66,271.64,301.83,272.63,1025.53,NaN,NaN,NaN
2017-05,581151.85,1981.77,3046.03,2039.15,1270.79,1698.01,3024.03,608.02,1623.52,1396.62,1459.06,1438.36,1173.14,62.33,803.36,1029.68,NaN,NaN,NaN,NaN
2017-06,496983.48,4000.05,2060.14,1433.12,1374.89,1627.85,1690.13,822.86,346.26,570.50,2348.45,2166.06,513.44,909.63,2284.89,NaN,NaN,NaN,NaN,NaN
2017-07,575074.59,3070.50,1824.74,1156.32,1220.36,1865.65,2553.19,250.36,413.96,2071.11,1163.02,1264.85,1409.38,981.78,NaN,NaN,NaN,NaN,NaN,NaN
2017-08,656910.93,5056.77,2229.03,1014.62,1858.42,2911.98,1864.71,1949.83,1800.03,1204.91,1460.16,1825.60,532.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-09,708537.84,3659.33,3182.57,1793.32,3226.19,2055.93,1067.34,965.33,1218.00,695.80,1336.99,326.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-10,755758.96,4443.59,1643.41,578.42,1486.94,1408.03,1167.97,2448.18,2349.37,2024.65,960.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11,1161110.78,8078.27,4119.57,1622.72,2398.32,1895.06,1133.36,1956.68,1367.53,678.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12,844398.24,2397.92,1922.78,2401.50,1959.48,2055.20,1258.70,284.96,1828.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01,1086077.48,3713.86,3865.81,3418.22,2663.14,1586.64,1393.54,1643.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02,970545.03,3490.42,4230.12,3518.60,2246.80,3050.56,1730.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-03,1134203.79,4445.02,3666.09,3264.78,1561.10,519.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04,1132945.38,5090.03,3693.24,1886.83,849.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-05,1120582.89,8365.17,2698.50,1886.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-06,992112.29,3123.97,1893.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07,1034038.76,4521.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08,980092.19,166.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
cohort_revenue_base = revenue_cohort_table.iloc[:,0]

revenue_retention = revenue_cohort_table.divide(cohort_revenue_base, axis=0) * 100
revenue_retention = revenue_retention.reindex(columns=range(0,21))
revenue_retention

cohort_index,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
order_month_cohort,,,,,,,,,,,,,,,,,,,,,
2016-09,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-10,100.0,NaN,NaN,NaN,NaN,NaN,0.195920,NaN,NaN,0.626892,...,0.099949,NaN,0.287860,NaN,0.670670,NaN,0.205197,NaN,0.675969,0.319264
2016-12,100.0,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01,100.0,0.124540,0.083620,0.065394,0.179523,0.050544,0.326918,0.076672,0.034301,NaN,...,0.048553,0.402752,0.256363,0.068310,0.076264,0.159912,0.258390,NaN,0.037129,NaN
2017-02,100.0,0.187383,0.199444,0.041498,0.402629,0.025938,0.240789,0.095872,0.162389,0.134686,...,0.158817,0.097599,0.138796,0.063493,0.047810,0.101947,0.187397,NaN,NaN,NaN
2017-03,100.0,0.416082,0.402672,0.425616,0.281404,0.332266,0.159755,0.205708,0.335535,0.055160,...,0.088155,0.219684,0.055304,0.159345,0.166331,0.047260,0.109609,NaN,NaN,NaN
2017-04,100.0,0.716594,0.229447,0.184994,0.462700,0.294821,0.508423,0.267545,0.235202,0.121950,...,0.083729,0.119227,0.066277,0.073643,0.066519,0.250217,NaN,NaN,NaN,NaN
2017-05,100.0,0.341007,0.524137,0.350881,0.218667,0.292180,0.520351,0.104623,0.279362,0.240319,...,0.247502,0.201865,0.010725,0.138236,0.177179,NaN,NaN,NaN,NaN,NaN
2017-06,100.0,0.804866,0.414529,0.288364,0.276647,0.327546,0.340078,0.165571,0.069672,0.114793,...,0.435841,0.103311,0.183030,0.459752,NaN,NaN,NaN,NaN,NaN,NaN
2017-07,100.0,0.533931,0.317305,0.201073,0.212209,0.324419,0.443975,0.043535,0.071984,0.360146,...,0.219945,0.245078,0.170722,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-08,100.0,0.769780,0.339320,0.154453,0.282903,0.443284,0.283860,0.296818,0.274014,0.183421,...,0.277907,0.081116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-09,100.0,0.516462,0.449174,0.253102,0.455331,0.290165,0.150640,0.136243,0.171903,0.098202,...,0.046053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-10,100.0,0.587964,0.217452,0.076535,0.196748,0.186307,0.154543,0.323937,0.310862,0.267896,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11,100.0,0.695736,0.354796,0.139756,0.206554,0.163211,0.097610,0.168518,0.117778,0.058419,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12,100.0,0.283980,0.227710,0.284404,0.232056,0.243392,0.149065,0.033747,0.216574,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01,100.0,0.341952,0.355942,0.314731,0.245207,0.146089,0.128309,0.151332,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02,100.0,0.359635,0.435850,0.362539,0.231499,0.314314,0.178338,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-03,100.0,0.391907,0.323230,0.287848,0.137638,0.045822,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04,100.0,0.449274,0.325986,0.166542,0.074937,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-05,100.0,0.746502,0.240812,0.168310,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-06,100.0,0.314881,0.190813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07,100.0,0.437289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08,100.0,0.016984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Export the retention table

In [138]:
revenue_retention.reset_index(inplace=True)

#revenue_retention.to_csv("revenue_retention_cohort.csv", index=False)

In [139]:
sales_dataset["revenue"].describe()

count    112650.000000
mean        140.644059
std         190.724394
min           6.080000
25%          55.220000
50%          92.320000
75%         157.937500
max        6929.310000
Name: revenue, dtype: float64

In [140]:
sales_dataset["revenue"].quantile([0.9,0.95,0.99])

0.90    257.5610
0.95    378.9595
0.99    923.2159
Name: revenue, dtype: float64

In [141]:
cohort_sizes = sales_dataset.groupby("order_month_cohort")["customer_unique_id"].nunique()

print(cohort_sizes)

order_month_cohort
2016-09       3
2016-10     305
2016-12       1
2017-01     754
2017-02    1705
2017-03    2595
2017-04    2339
2017-05    3560
2017-06    3114
2017-07    3843
2017-08    4149
2017-09    4090
2017-10    4412
2017-11    7217
2017-12    5442
2018-01    6983
2018-02    6422
2018-03    6947
2018-04    6709
2018-05    6604
2018-06    5934
2018-07    6054
2018-08    6238
Freq: M, Name: customer_unique_id, dtype: int64

*The first cohor are very small that could lead to instable metrics*

## Customer Analytics

**Total revenue per customer**

In [142]:
customer_revenue = sales_dataset.groupby("customer_unique_id")["revenue"].sum()
customer_revenue

customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2     141.90
0000b849f77a49e4a4ce2b2a4ca5be3f      27.19
0000f46a3911fa3c0805444483337064      86.22
0000f6ccb0745a6a4b88665a16c9f078      43.62
0004aac84e0df4da2b147fca70cf8255     196.89
                                     ...
fffcf5a5ff07b0908bd4e2dbc735a684    2067.42
fffea47cd6d3cc0a88bd621562a9d061      84.58
ffff371b4d645b6ecea244b27531430a     112.46
ffff5962728ec6157033ef9805bacc48     133.69
ffffd2657e2aad2907e67c3e9daecbeb      71.56
Name: revenue, Length: 95420, dtype: float64

**Count of command**

In [143]:
customer_orders = sales_dataset.groupby("customer_unique_id")["order_id"].nunique()
customer_orders.value_counts()

1     92507
2      2673
3       192
4        29
5         9
6         5
7         3
9         1
16        1
Name: order_id, dtype: int64

**Average order value**

In [144]:
avg_order_value = customer_revenue / customer_orders
avg_order_value

customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2     141.90
0000b849f77a49e4a4ce2b2a4ca5be3f      27.19
0000f46a3911fa3c0805444483337064      86.22
0000f6ccb0745a6a4b88665a16c9f078      43.62
0004aac84e0df4da2b147fca70cf8255     196.89
                                     ...
fffcf5a5ff07b0908bd4e2dbc735a684    2067.42
fffea47cd6d3cc0a88bd621562a9d061      84.58
ffff371b4d645b6ecea244b27531430a     112.46
ffff5962728ec6157033ef9805bacc48     133.69
ffffd2657e2aad2907e67c3e9daecbeb      71.56
Length: 95420, dtype: float64

**Customer Analytics table creation**

In [145]:
customer_analytics = rfm.copy()

customer_analytics["total_revenue"] = customer_revenue
customer_analytics["total_orders"] = customer_orders
customer_analytics["avg_order_value"] = avg_order_value
customer_analytics

,customer_unique_id,recency,frequency,monetary,r_score,f_score,m_score,rfm_score,segment,total_revenue,total_orders,avg_order_value
0,0000366f3b9a7992bf8c76cfdf3221e2,115,1,141.90,4,1,4,414,Potential Loyalists,NaN,NaN,NaN
1,0000b849f77a49e4a4ce2b2a4ca5be3f,118,1,27.19,4,1,1,411,Potential Loyalists,NaN,NaN,NaN
2,0000f46a3911fa3c0805444483337064,541,1,86.22,1,1,2,112,Lost,NaN,NaN,NaN
3,0000f6ccb0745a6a4b88665a16c9f078,325,1,43.62,2,1,1,211,Lost,NaN,NaN,NaN
4,0004aac84e0df4da2b147fca70cf8255,292,1,196.89,2,1,4,214,Lost,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
95415,fffcf5a5ff07b0908bd4e2dbc735a684,451,1,2067.42,1,1,5,115,Lost,NaN,NaN,NaN
95416,fffea47cd6d3cc0a88bd621562a9d061,266,1,84.58,3,1,2,312,Lost,NaN,NaN,NaN
95417,ffff371b4d645b6ecea244b27531430a,572,1,112.46,1,1,3,113,Lost,NaN,NaN,NaN
95418,ffff5962728ec6157033ef9805bacc48,123,1,133.69,4,1,4,414,Potential Loyalists,NaN,NaN,NaN
95419,ffffd2657e2aad2907e67c3e9daecbeb,488,1,71.56,1,1,2,112,Lost,NaN,NaN,NaN

**Export customer analytics table**

In [146]:
customer_analytics.reset_index(inplace=True)

#customer_analytics.to_csv("customer_analytics_table.csv", index=False)

## Retention Dataset creation

**Merging customers and orders**

In [147]:
df = orders.merge(customers, on ="customer_id", how="left")
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

**Creating revenue table**

In [148]:
order_revenue = order_items.groupby("order_id").agg({
    "price":"sum",
    "freight_value": "sum"
}).reset_index()

order_revenue["total_revenue"] = order_revenue["price"] + order_revenue["freight_value"]
order_revenue.head()

                           order_id   price  freight_value  total_revenue
0  00010242fe8c5a6d1ba2dd792cb16214   58.90          13.29          72.19
1  00018f77f2f0320c557190d7a144bdd3  239.90          19.93         259.83
2  000229ec398224ef6ca0657da4fc703e  199.00          17.87         216.87
3  00024acbcdf0a6daa1e931b038114c75   12.99          12.79          25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9  199.90          18.14         218.04

**Merging customers, orders and revenue**

In [149]:
df = df.merge(order_revenue, on="order_id", how="left")
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,price,freight_value,total_revenue
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,29.99,8.72,38.71
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,118.70,22.76,141.46
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,159.90,19.22,179.12
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,45.00,27.20,72.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,19.90,8.72,28.62

**Keeping only necessary column**

In [150]:
df = df[[
    "order_id",
    "customer_unique_id",
    "order_purchase_timestamp",
    "total_revenue"
]]
df.head()

,order_id,customer_unique_id,order_purchase_timestamp,total_revenue
0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,2017-10-02 10:56:33,38.71
1,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,2018-07-24 20:41:37,141.46
2,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,2018-08-08 08:38:49,179.12
3,949d5b44dbf5de918fe9c16f97b45f8a,7c142cf63193a1473d2e66489a9ae977,2017-11-18 19:28:06,72.20
4,ad21c59c0840e6cb83a9ceb5573f8159,72632f0f9dd73dfee390c9b22eb56dd6,2018-02-13 21:18:39,28.62

In [151]:
df.to_csv("retention_dataset.csv", index=False)